import { Pool } from 'pg';
import { createHash } from 'node:crypto';

export type BankRow={date:string;valueDate?:string;narration:string;reference?:string;debit:number;credit:number;balance?:number};
const clean=(v:string)=>v.trim().replace(/^"|"$/g,'').trim();
export function parseCsv(input:string):string[][]{const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<input.length;i++){const ch=input[i];if(ch==='"'){if(quoted&&input[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&input[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[];}else cell+=ch;}if(cell||row.length){row.push(cell);if(row.some(x=>x.trim()))rows.push(row);}return rows;}
const idx=(h:string[],names:string[])=>{const a=h.map(x=>clean(x).toLowerCase().replace(/[^a-z0-9]/g,''));return names.map(n=>a.indexOf(n)).find(i=>i>=0)??-1};
const amount=(v:string)=>{const n=Number(clean(v).replace(/,/g,'').replace(/[₹$]/g,''));return Number.isFinite(n)?Math.abs(n):0};
const toDate=(v:string)=>{const s=clean(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(!m)throw new Error(`Unsupported date: ${s}`);const y=m[3].length===2?`20${m[3]}`:m[3];return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`};
export function normalizeBankCsv(csv:string){const m=parseCsv(csv);if(m.length<2)throw new Error('CSV must contain a header and data');const h=m[0].map(clean);const di=idx(h,['date','transactiondate','txndate']),ni=idx(h,['narration','description','particulars','remarks']),ri=idx(h,['reference','refno','chequeno','transactionid']),db=idx(h,['debit','withdrawal','withdrawals','dr']),cr=idx(h,['credit','deposit','deposits','cr']),bi=idx(h,['balance','closingbalance','runningbalance']),vi=idx(h,['valuedate']);if(di<0||ni<0||(db<0&&cr<0))throw new Error('CSV needs Date, Narration/Description and Debit/Credit columns');const rows:BankRow[]=[];const errors:string[]=[];m.slice(1).forEach((r,i)=>{try{const debit=db>=0?amount(r[db]??''):0,credit=cr>=0?amount(r[cr]??''):0;if((debit===0&&credit===0)||(debit>0&&credit>0))throw new Error('Invalid debit/credit');rows.push({date:toDate(r[di]??''),valueDate:vi>=0?toDate(r[vi]??r[di]??''):toDate(r[di]??''),narration:clean(r[ni]??''),reference:ri>=0?clean(r[ri]??''):undefined,debit,credit,balance:bi>=0?amount(r[bi]??''):undefined});}catch(e){errors.push(`row ${i+2}: ${e instanceof Error?e.message:'invalid row'}`)}});return{rows,errors};}
const rowHash=(org:string,bank:string,r:BankRow)=>createHash('sha256').update(JSON.stringify([org,bank,r])).digest('hex');
export async function importBankCsv(pool:Pool,args:{organizationId:string;bankAccountId:string;fileName:string;csv:string}){const p=normalizeBankCsv(args.csv);const c=await pool.connect();let inserted=0,duplicates=0;try{await c.query('BEGIN');const batch=(await c.query(`INSERT INTO bank_import_batches(organization_id,bank_account_id,file_name,row_count) VALUES($1,$2,$3,$4) RETURNING id`,[args.organizationId,args.bankAccountId,args.fileName,p.rows.length])).rows[0].id;for(const r of p.rows){const x=await c.query(`INSERT INTO bank_transactions(organization_id,bank_account_id,transaction_date,value_date,narration,reference,debit,credit,balance,source_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(organization_id,source_hash) DO NOTHING RETURNING id`,[args.organizationId,args.bankAccountId,r.date,r.valueDate,r.narration,r.reference??null,r.debit,r.credit,r.balance??null,rowHash(args.organizationId,args.bankAccountId,r)]);if(x.rowCount)inserted++;else duplicates++;}await c.query(`UPDATE bank_import_batches SET inserted_count=$1,duplicate_count=$2,error_count=$3,errors=$4 WHERE id=$5`,[inserted,duplicates,p.errors.length,JSON.stringify(p.errors),batch]);await c.query('COMMIT');return{batchId:batch,rows:p.rows.length,inserted,duplicates,errors:p.errors};}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}
export async function reconcileBank(pool:Pool,org:string,bankAccountId:string){const c=await pool.connect();let matched=0,suggested=0;try{await c.query('BEGIN');const txs=(await c.query(`SELECT * FROM bank_transactions WHERE organization_id=$1 AND bank_account_id=$2 AND match_status='UNMATCHED' ORDER BY transaction_date,id`,[org,bankAccountId])).rows;for(const t of txs){const amount=Number(t.debit||t.credit),side=t.credit>0?'debit':'credit';const q=await c.query(`SELECT je.id,je.entry_date,je.voucher_number,je.narration FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_id WHERE je.organization_id=$1 AND je.status='POSTED' AND jl.account_id=(SELECT id FROM accounts WHERE organization_id=$1 AND code='1000') AND jl.${side} BETWEEN $2-0.01 AND $2+0.01 AND je.entry_date BETWEEN ($3::date-3) AND ($3::date+3) AND NOT EXISTS(SELECT 1 FROM bank_transactions bx WHERE bx.matched_journal_id=je.id AND bx.organization_id=$1) ORDER BY ABS(je.entry_date-$3::date),je.created_at LIMIT 1`,[org,amount,t.transaction_date]);const best=q.rows[0];if(!best)continue;const text=(String(t.narration)+' '+String(t.reference??'')).toLowerCase(),jt=(String(best.narration)+' '+String(best.voucher_number)).toLowerCase(),hit=text.split(/\s+/).some((w:string)=>w.length>3&&jt.includes(w)),confidence=hit?98:90,status=confidence>=95?'MATCHED':'SUGGESTED';if(status==='MATCHED'){await c.query(`UPDATE bank_transactions SET matched_journal_id=$1,match_status='MATCHED',match_confidence=$2 WHERE id=$3`,[best.id,confidence,t.id]);matched++;}else{await c.query(`UPDATE bank_transactions SET match_status='SUGGESTED',match_confidence=$1 WHERE id=$2`,[confidence,t.id]);suggested++;}await c.query(`INSERT INTO bank_reconciliations(organization_id,bank_transaction_id,journal_id,status,confidence,reason) VALUES($1,$2,$3,$4,$5,$6)`,[org,t.id,best.id,status,confidence,hit?'Amount/date/text match':'Amount/date match']);}await c.query('COMMIT');return{processed:txs.length,matched,suggested};}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}
