import { Router } from 'express';
import { z } from 'zod';
import { Pool } from 'pg';
import { buildGstr1,buildGstr3b,buildTds,importGstr2b,reconcileGstr2b,validateGstDocument } from './part3-tax.js';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export function part3Routes(pool:Pool,org:string){const r=Router();
 r.post('/gst/validate',async(q,s)=>{try{s.json(validateGstDocument(z.object({invoiceNumber:z.string(),invoiceDate:date.optional(),supplierGstin:z.string().optional(),taxableValue:z.number().nonnegative(),cgst:z.number().nonnegative(),sgst:z.number().nonnegative(),igst:z.number().nonnegative(),cess:z.number().nonnegative(),filingPeriod:z.string().optional()}).parse(q.body)));}catch(e){s.status(400).json({error:e instanceof Error?e.message:'Invalid GST document'});}});
 r.post('/gst/2b/import',async(q,s)=>{try{const b=z.object({records:z.array(z.object({invoiceNumber:z.string(),invoiceDate:date.optional(),supplierGstin:z.string().optional(),taxableValue:z.number().nonnegative(),cgst:z.number().nonnegative(),sgst:z.number().nonnegative(),igst:z.number().nonnegative(),cess:z.number().nonnegative(),filingPeriod:z.string().optional()})).min(1)}).parse(q.body);s.status(201).json(await importGstr2b(pool,org,b.records));}catch(e){s.status(400).json({error:e instanceof Error?e.message:'GSTR-2B import failed'});}});
 r.get('/gst/2b',async(_q,s)=>s.json((await pool.query(`SELECT * FROM gst_2b_records WHERE organization_id=$1 ORDER BY invoice_date DESC,created_at DESC LIMIT 1000`,[org])).rows));
 r.post('/gst/2b/reconcile',async(_q,s)=>{try{s.json({summary:await reconcileGstr2b(pool,org)});}catch(e){s.status(400).json({error:e instanceof Error?e.message:'GSTR-2B reconciliation failed'});}});
 r.get('/gst/reconciliation',async(_q,s)=>s.json((await pool.query(`SELECT gr.*,g.invoice_id,i.invoice_number,p.gstin FROM gst_reconciliations gr LEFT JOIN gst_transactions g ON g.id=gr.gst_transaction_id LEFT JOIN invoices i ON i.id=g.invoice_id LEFT JOIN parties p ON p.id=i.party_id WHERE gr.organization_id=$1 ORDER BY gr.created_at DESC LIMIT 1000`,[org])).rows));
 r.get('/gst/gstr1',async(q,s)=>{try{const p=z.object({from:date,to:date}).parse(q.query);s.json(await buildGstr1(pool,org,p.from,p.to));}catch(e){s.status(400).json({error:e instanceof Error?e.message:'GSTR-1 preparation failed'});}});
 r.get('/gst/gstr3b',async(q,s)=>{try{const p=z.object({from:date,to:date}).parse(q.query);s.json(await buildGstr3b(pool,org,p.from,p.to));}catch(e){s.status(400).json({error:e instanceof Error?e.message:'GSTR-3B preparation failed'});}});
 r.get('/tds/return',async(q,s)=>{try{const p=z.object({from:date,to:date}).parse(q.query);s.json(await buildTds(pool,org,p.from,p.to));}catch(e){s.status(400).json({error:e instanceof Error?e.message:'TDS preparation failed'});}});
 r.get('/summary',async(_q,s)=>{const [gst,tds,recon]=await Promise.all([pool.query(`SELECT direction,COALESCE(SUM(taxable_value),0)::numeric taxable,COALESCE(SUM(cgst+sgst+igst+cess),0)::numeric tax FROM gst_transactions WHERE organization_id=$1 GROUP BY direction`,[org]),pool.query(`SELECT COALESCE(SUM(base_amount),0)::numeric base,COALESCE(SUM(tds_amount),0)::numeric tax,COUNT(*)::int count FROM tds_transactions WHERE organization_id=$1`,[org]),pool.query(`SELECT match_status,count(*)::int count FROM gst_reconciliations WHERE organization_id=$1 GROUP BY match_status`,[org])]);s.json({gst:gst.rows,tds:tds.rows[0],reconciliation:recon.rows});});
 return r;}
