import express from 'express';
import { Pool } from 'pg';
import { z } from 'zod';
import { postJournal, trialBalance, financialSummary } from './accounting.js';
import { complianceSummary } from './compliance.js';

const app=express(); app.use(express.json({limit:'2mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL??'postgres://ai_tax:ai_tax_dev@localhost:5432/ai_tax'});
const ORG='00000000-0000-0000-0000-000000000001'; const PERIOD='00000000-0000-0000-0000-000000000101';
const money=z.number().finite().nonnegative();

app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true,service:'ai-tax-api'})}catch{res.status(503).json({ok:false,database:false})}});
app.get('/api/dashboard',async(_req,res)=>{try{const [org,tb,summary,exceptions]=await Promise.all([pool.query('SELECT id,name,legal_name,pan,gstin,entity_type,state_code FROM organizations WHERE id=$1',[ORG]),trialBalance(pool,ORG),financialSummary(pool,ORG),pool.query("SELECT severity,title,description,status FROM exceptions WHERE organization_id=$1 AND status='OPEN' ORDER BY created_at DESC LIMIT 10",[ORG])]);const totals=tb.reduce((a,r)=>({debit:a.debit+Number(r.debit),credit:a.credit+Number(r.credit)}),{debit:0,credit:0});res.json({organization:org.rows[0],trialBalance:tb,summary,totals,exceptions:exceptions.rows})}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Dashboard failed'})}});
app.get('/api/accounts',async(_req,res)=>res.json((await pool.query('SELECT id,code,name,type,parent_id FROM accounts WHERE organization_id=$1 ORDER BY code',[ORG])).rows));
app.get('/api/parties',async(_req,res)=>res.json((await pool.query('SELECT id,name,kind,gstin,pan,state_code FROM parties WHERE organization_id=$1 ORDER BY name',[ORG])).rows));
app.get('/api/journals',async(_req,res)=>res.json((await pool.query(`SELECT je.id,je.entry_date,je.voucher_number,je.voucher_type,je.narration,je.status,COALESCE(SUM(jl.debit),0)::numeric debit,COALESCE(SUM(jl.credit),0)::numeric credit FROM journal_entries je JOIN journal_lines jl ON jl.journal_id=je.id WHERE je.organization_id=$1 GROUP BY je.id ORDER BY je.entry_date DESC,je.created_at DESC LIMIT 100`,[ORG])).rows));
app.get('/api/journals/:id',async(req,res)=>{const j=await pool.query('SELECT * FROM journal_entries WHERE id=$1 AND organization_id=$2',[req.params.id,ORG]);if(!j.rowCount)return res.status(404).json({error:'Journal not found'});const lines=await pool.query(`SELECT jl.*,a.code,a.name FROM journal_lines jl JOIN accounts a ON a.id=jl.account_id WHERE jl.journal_id=$1 ORDER BY jl.id`,[req.params.id]);res.json({entry:j.rows[0],lines:lines.rows})});

const journalSchema=z.object({voucherNumber:z.string().trim().min(1).max(60),voucherType:z.enum(['SALES','PURCHASE','RECEIPT','PAYMENT','CONTRA','JOURNAL','ADJUSTMENT']),entryDate:z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),narration:z.string().trim().min(1).max(500),lines:z.array(z.object({accountId:z.string().uuid(),partyId:z.string().uuid().optional(),description:z.string().max(500).optional(),debit:money.default(0),credit:money.default(0)})).min(2)});
app.post('/api/journals',async(req,res)=>{const p=journalSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid journal',details:p.error.flatten()});try{const id=await postJournal(pool,{organizationId:ORG,financialPeriodId:PERIOD,...p.data});res.status(201).json({id,status:'POSTED'})}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Unable to post journal'})}});

const partySchema=z.object({name:z.string().trim().min(1).max(200),kind:z.enum(['CUSTOMER','VENDOR','BOTH']),gstin:z.string().trim().max(15).optional(),pan:z.string().trim().max(10).optional(),stateCode:z.string().regex(/^\\d{2}$/).optional()});
app.post('/api/parties',async(req,res)=>{const p=partySchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid party',details:p.error.flatten()});const r=await pool.query(`INSERT INTO parties(organization_id,name,kind,gstin,pan,state_code) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[ORG,p.data.name,p.data.kind,p.data.gstin??null,p.data.pan??null,p.data.stateCode??null]);res.status(201).json(r.rows[0])});

const invoiceSchema=z.object({invoiceNumber:z.string().trim().min(1).max(80),invoiceDate:z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),documentType:z.enum(['SALES','PURCHASE','CREDIT_NOTE','DEBIT_NOTE']),partyId:z.string().uuid().optional(),placeOfSupply:z.string().regex(/^\\d{2}$/).optional(),reverseCharge:z.boolean().default(false),items:z.array(z.object({description:z.string().min(1),hsnSac:z.string().max(20).optional(),quantity:z.number().positive(),unitPrice:money,gstRate:z.number().nonnegative(),cgst:money.default(0),sgst:money.default(0),igst:money.default(0),cess:money.default(0)})).min(1)});
app.post('/api/invoices',async(req,res)=>{const p=invoiceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid invoice',details:p.error.flatten()});const d=p.data;const taxable=d.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0);const cgst=d.items.reduce((s,i)=>s+i.cgst,0),sgst=d.items.reduce((s,i)=>s+i.sgst,0),igst=d.items.reduce((s,i)=>s+i.igst,0),cess=d.items.reduce((s,i)=>s+i.cess,0),total=taxable+cgst+sgst+igst+cess;const c=await pool.connect();try{await c.query('BEGIN');const v=await c.query(`INSERT INTO invoices(organization_id,invoice_number,invoice_date,document_type,party_id,taxable_value,cgst,sgst,igst,cess,total,place_of_supply,reverse_charge,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'VALIDATED') RETURNING *`,[ORG,d.invoiceNumber,d.invoiceDate,d.documentType,d.partyId??null,taxable,cgst,sgst,igst,cess,total,d.placeOfSupply??null,d.reverseCharge]);for(const i of d.items)await c.query(`INSERT INTO invoice_items(invoice_id,description,hsn_sac,quantity,unit_price,taxable_value,gst_rate,cgst,sgst,igst,cess,total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[v.rows[0].id,i.description,i.hsnSac??null,i.quantity,i.unitPrice,i.quantity*i.unitPrice,i.gstRate,i.cgst,i.sgst,i.igst,i.cess,i.quantity*i.unitPrice+i.cgst+i.sgst+i.igst+i.cess]);await c.query(`INSERT INTO audit_logs(organization_id,actor_type,action,entity_type,entity_id,after_data) VALUES($1,'USER','INVOICE_CREATED','invoice',$2,$3)`,[ORG,v.rows[0].id,JSON.stringify(d)]);await c.query('COMMIT');res.status(201).json(v.rows[0])}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e instanceof Error?e.message:'Unable to create invoice'})}finally{c.release()}});
app.get('/api/invoices',async(_req,res)=>res.json((await pool.query(`SELECT i.*,p.name party_name FROM invoices i LEFT JOIN parties p ON p.id=i.party_id WHERE i.organization_id=$1 ORDER BY i.invoice_date DESC,i.created_at DESC LIMIT 200`,[ORG])).rows));
app.get('/api/invoices/:id',async(req,res)=>{const i=await pool.query('SELECT i.*,p.name party_name,p.gstin party_gstin FROM invoices i LEFT JOIN parties p ON p.id=i.party_id WHERE i.id=$1 AND i.organization_id=$2',[req.params.id,ORG]);if(!i.rowCount)return res.status(404).json({error:'Invoice not found'});const items=await pool.query('SELECT * FROM invoice_items WHERE invoice_id=$1 ORDER BY id',[req.params.id]);res.json({invoice:i.rows[0],items:items.rows})});

app.get('/api/ledger/:accountId',async(req,res)=>{const r=await pool.query(`SELECT je.entry_date,je.voucher_number,je.voucher_type,je.narration,jl.description,jl.debit,jl.credit FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_id WHERE je.organization_id=$1 AND jl.account_id=$2 AND je.status='POSTED' ORDER BY je.entry_date,je.created_at`,[ORG,req.params.accountId]);let b=0;res.json(r.rows.map(x=>{b+=Number(x.debit)-Number(x.credit);return {...x,balance:b.toFixed(2)}}))});
app.get('/api/reports/summary',async(_req,res)=>res.json(await financialSummary(pool,ORG)));
app.get('/api/reports/trial-balance',async(_req,res)=>res.json(await trialBalance(pool,ORG)));
app.get('/api/compliance/summary',async(_req,res)=>res.json(await complianceSummary(pool,ORG)));
app.get('/',(_req,res)=>res.sendFile('index.html',{root:'public'})); app.use(express.static('public'));
const port=Number(process.env.PORT??3000);app.listen(port,()=>console.log(`AI TAX running on http://localhost:${port}`));
